using System;
using Postgrest.Models;
using Postgrest.Attributes;

namespace API.Models;

[Table("bus")]
public class Bus : BaseModel
{
    [PrimaryKey("id")]
    public int Id { get; set; }

    [Column("bus_name")]
    public string bus_name { get; set; } = "";

    [Column("is_seat_available")] // Maps the "Name" property to the "name" column in the table
    public string isSeatAvailable { get; set; } = "01111111111111111111111111111111111111111";

    [Column("registration_code")] // Maps the "Code" property to the "code" column in the table
    public string registrationCode { get; set; } = string.Empty;

    [Column("is_active")] // Maps the "IsActive" property to the "is_active" column in the table
    public bool IsActive { get; set; } = true;

    [Column("bus_model")] // Maps the "Code" property to the "code" column in the table
    public string busModel { get; set; } = string.Empty;

    // Parameterless constructor (required by Supabase)
    public Bus() : base() // Call the base constructor from BaseModel
    {
        // Id will be auto-generated by Postgrest (no need to manually set it here)
        // Name, Code, and IsActive will be initialized in the property definitions
    }
}
