using Postgrest.Models;
using Postgrest.Attributes;

namespace API.Models;

[Table("trips")]
public class Trip : BaseModel
{
    [PrimaryKey("id")]
    public Guid Id { get; set; }

    [Column("departure_location_id")]
    public string DepartureLocationId { get; set; } = string.Empty;

    [Column("destination_location_id")]
    public string DestinationLocationId { get; set; } = string.Empty;

    [Column("departure_time")]
    public TimeOnly DepartureTime { get; set; }

    [Column("arrival_time")]
    public TimeOnly ArrivalTime { get; set; }

    [Column("fare")]
    public float Fare { get; set; } = 0.00F;

    [Column("is_available")]
    public bool IsAvailable { get; set; } = true;

    [Column("days_available")]
    public int[] DaysAvailable { get; set; } = new int[] { 0, 1, 2, 3, 4, 5, 6 };

    // Parameterless constructor (required by Supabase)
    public Trip() : base() // Call the base constructor from BaseModel
    {
        // Id will be auto-generated by Postgrest (no need to manually set it here)
        // Name, Code, and IsActive will be initialized in the property definitions
    }
}
